export type TCodigosSiigo = {
  codigo      : number
  linea       : number
  grupo       : number
  enSiigo     : boolean
  idProducto ?: number
  nombre     ?: string
  ref        ?: string
}

export const columnasSiigo = [
  { name: "enSiigo",  label: "En Siigo",  CSVOculto: true,      format: ( value : any)=> !!value ? "✅" : "❌" },
  { name: "linea",    label: "LÍNEA",     clase: "fuente-mono"  },
  { name: "grupo",                        clase: "fuente-mono"  },
  { name: "codigo",   label: "PRODUCTO",  clase: "fuente-mono"  },
  { name: "nombre",   label: "DESCRIPCIÓN"  },
  { name: "ref",      label: "REFERENCIA DE FÁBRICA"  },
  { name: "CÓDIGO DE BARRAS"  },
  { name: "PRECIO 1", CSVvalor: "0" },
  { name: 'PRECIO 2', CSVvalor: '0' },
  { name: 'PRECIO 3', CSVvalor: '0' },
  { name: 'PRECIO 4', CSVvalor: '0' },
  { name: 'PRECIO 5', CSVvalor: '0' },
  { name: 'PRECIO 6', CSVvalor: '0' },
  { name: 'PRECIO 7', CSVvalor: '0' },
  { name: 'PRECIO 8', CSVvalor: '0' },
  { name: 'PRECIO 9', CSVvalor: '0' },
  { name: 'PRECIO 10', CSVvalor: '0' },
  { name: 'PRECIO 11', CSVvalor: '0' },
  { name: 'PRECIO 12', CSVvalor: '0' },
  { name: 'IVA INCLUIDO', CSVvalor: 'N' },
  { name: 'PORCENTAJE DE IVA', CSVvalor: '19' },
  { name: 'EXISTENCIA MÁXIMA', CSVvalor: '0' },
  { name: 'EXISTENCIA MÍNIMA', CSVvalor: '0' },
  { name: 'TIEMPO DE REPOSICIÓN', CSVvalor: '0' },
  { name: 'COSTO DE COMPRA', CSVvalor: '0' },
  { name: 'UNIDAD', CSVvalor: 'UND' },
  { name: 'CÓDIGO DE PRODUCTO EQUIVALENTE', CSVvalor: '0' },
  { name: 'DESCRIPCIÓN PRODUCTO EQUIVALENTE', CSVvalor: '' },
  { name: 'MARCA', CSVvalor: '' },
  { name: 'MANEJA FACTOR DE CONVERSIÓN', CSVvalor: 'N' },
  { name: 'NOMBRE FACTOR DE CONVERSIÓN 1', CSVvalor: '' },
  { name: 'NOMBRE FACTOR DE CONVERSIÓN 2', CSVvalor: '' },
  { name: 'NOMBRE FACTOR DE CONVERSIÓN 3', CSVvalor: '' },
  { name: 'NOMBRE FACTOR DE CONVERSIÓN 4', CSVvalor: '' },
  { name: 'NOMBRE FACTOR DE CONVERSIÓN 5', CSVvalor: '' },
  { name: 'OPERANDO 1', CSVvalor: '' },
  { name: 'OPERANDO 2', CSVvalor: '' },
  { name: 'OPERANDO 3', CSVvalor: '' },
  { name: 'OPERANDO 4', CSVvalor: '' },
  { name: 'OPERANDO 5', CSVvalor: '' },
  { name: 'FACTOR 1', CSVvalor: '0' },
  { name: 'FACTOR 2', CSVvalor: '0' },
  { name: 'FACTOR 3', CSVvalor: '0' },
  { name: 'FACTOR 4', CSVvalor: '0' },
  { name: 'FACTOR 5', CSVvalor: '0' },
  { name: 'TARIFA', CSVvalor: '3' },
  { name: 'UBICACIÓN', CSVvalor: '' },
  { name: 'DISCRIMINAR IVA EN LA IMPRESIÓN', CSVvalor: 'S' },
  { name: 'ACTIVO', CSVvalor: 'S' },
  { name: 'PESO', CSVvalor: '0' },
  { name: 'ENVIAR A ISIIGO', CSVvalor: '' },
  { name: 'NIT PROVEEDOR 1', CSVvalor: '0' },
  { name: 'NIT PROVEEDOR 2', CSVvalor: '0' },
  { name: 'NIT PROVEEDOR 3', CSVvalor: '0' },
  { name: 'NIT PROVEEDOR 4', CSVvalor: '0' },
  { name: 'SUCURSAL PROVEEDOR 1', CSVvalor: '0' },
  { name: 'SUCURSAL PROVEEDOR 2', CSVvalor: '0' },
  { name: 'SUCURSAL PROVEEDOR 3', CSVvalor: '0' },
  { name: 'SUCURSAL PROVEEDOR 4', CSVvalor: '0' },
  { name: 'AÑO ULTIMA COMPRA 1', CSVvalor: '0' },
  { name: 'MES ULTIMA COMPRA 1', CSVvalor: '0' },
  { name: 'DÍA ULTIMA COMPRA 1', CSVvalor: '0' },
  { name: 'AÑO ULTIMA COMPRA 2', CSVvalor: '0' },
  { name: 'MES ULTIMA COMPRA 2', CSVvalor: '0' },
  { name: 'DÍA ULTIMA COMPRA 2', CSVvalor: '0' },
  { name: 'AÑO ULTIMA COMPRA 3', CSVvalor: '0' },
  { name: 'MES ULTIMA COMPRA 3', CSVvalor: '0' },
  { name: 'DÍA ULTIMA COMPRA 3', CSVvalor: '0' },
  { name: 'AÑO ULTIMA COMPRA 4', CSVvalor: '0' },
  { name: 'MES ULTIMA COMPRA 4', CSVvalor: '0' },
  { name: 'DÍA ULTIMA COMPRA 4', CSVvalor: '0' },
  { name: 'VALOR ÚLTIMA COMPRA 1', CSVvalor: '0' },
  { name: 'VALOR ÚLTIMA COMPRA 2', CSVvalor: '0' },
  { name: 'VALOR ÚLTIMA COMPRA 3', CSVvalor: '0' },
  { name: 'VALOR ÚLTIMA COMPRA 4', CSVvalor: '0' },
  { name: 'DESCRIPCIÓN LARGA', CSVvalor: '' },
  { name: 'MANEJA PESO EN CAJERO', CSVvalor: 'N' },
  { name: 'MANEJA MÁXIMOS Y MÍNIMOS PARA PRODUCTOS', CSVvalor: 'N' },
  { name: 'COSTO UNITARIO', CSVvalor: '0' },
  { name: 'MODELO', CSVvalor: '' },
  { name: 'UNIDAD DE MEDIDA FACTURA ELECTRÓNICA', CSVvalor: '' },
  { name: 'CÓDIGO ARANCELARIO', CSVvalor: '' },
  { name: 'UNIDAD MEDIDA DE CONVERSIÓN 1 FACTURA ELECTRÓNICA', CSVvalor: '' },
  { name: 'UNIDAD MEDIDA DE CONVERSIÓN 2 FACTURA ELECTRÓNICA', CSVvalor: '' },
  { name: 'UNIDAD MEDIDA DE CONVERSIÓN 3 FACTURA ELECTRÓNICA', CSVvalor: '' },
  { name: 'UNIDAD MEDIDA DE CONVERSIÓN 4 FACTURA ELECTRÓNICA', CSVvalor: '' },
  { name: 'UNIDAD MEDIDA DE CONVERSIÓN 5 FACTURA ELECTRÓNICA', CSVvalor: '' },
  { name: 'APLICA IMPOCONSUMO BOLSA PLASTICA FACTURA ELECTRÓN', CSVvalor: 'N' }
]